name: webrtc_server
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0-124.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.3.0
  web_socket_channel: ^2.4.0
  flutter_webrtc: ^0.13.1
  cupertino_icons: ^1.0.8
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  provider: ^6.1.4
  intl: ^0.20.2

flutter:

  uses-material-design: true
